# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  persistCredentials: true
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |
    git config --global user.email $(GITHUBUSEREMAIL)
    git config --global user.name $(GITHUBUSERNAME)
    git checkout -b $(Build.BuildId)
    git add .
    git commit -m "Automated PR from Azure Pipelines"
    git push -u origin $(Build.BuildId)
    
  displayName: 'Create PR on Github'
  # curl -H "Authorization: token $(githubAccessToken)" -X POST -d "{\"title\":\"Automated PR from Azure Pipelines\", \"body\":\"Please review and merge this PR\",\"head\":\"$(Build.BuildId)\",\"base\":\"$(githubTargetBranch)\"}" "https://api.github.com/repos/$(githubRepo)/pulls"